- name: Setup ARC
  hosts: localhost
  tasks:
    #   NAMESPACE="arc-systems"
    #   helm install arc \
    #     --namespace "${NAMESPACE}" \
    #     --create-namespace \
    #     oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller

    - name: Install ARC Controller
      kubernetes.core.helm:
        name: arc
        create_namespace: true
        release_namespace: arc-systems
        chart_ref: "oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller"

    #     INSTALLATION_NAME="arc-runner-set"
    #     NAMESPACE="arc-runners"
    #     GITHUB_CONFIG_URL="https://github.com/<your_enterprise/org/repo>"
    #     GITHUB_PAT="<PAT>"
    #     helm install "${INSTALLATION_NAME}" \
    #     --namespace "${NAMESPACE}" \
    #     --create-namespace \
    #     --set githubConfigUrl="${GITHUB_CONFIG_URL}" \
    #     --set githubConfigSecret.github_token="${GITHUB_PAT}" \
    #     oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set

    - name: Configure runner scale set
      kubernetes.core.helm:
        name: arc-runner-set
        create_namespace: true
        release_namespace: arc-runners
        chart_ref: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
